# Generated by Django 4.2.1 on 2023-06-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("dni", models.CharField(default="00000000", max_length=20)),
                ("fecha_de_nacimiento", models.DateField(default="2000-01-01")),
                ("edad", models.CharField(default="0", max_length=3)),
                (
                    "rama",
                    models.CharField(
                        choices=[
                            ("manada", "Manada"),
                            ("unidad", "Unidad"),
                            ("caminantes", "Caminantes"),
                            ("rovers", "Rovers"),
                            ("adultos", "Adultos"),
                        ],
                        default="manada",
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("presente", models.BooleanField(default=False)),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asistencia.beneficiario",
                    ),
                ),
            ],
        ),
    ]
